### ISSUE TITLE
URL gets cut off

### ISSUE THREAD

**Issue by cerealisgoodforyou** [Plompi/VinURL#11]
The URL field has a maximum length which is not enough for many links, resulting in the mod failing to download the song.

**Comment by Plompi** [comment]
currently the limit is set to 200 characters, which should sufficient for most uses. which links do exceed said threshhold? If its really an issue, i can set the max length to a higher value. As a side note, this behavior can be bypassed by using the /vinurl set command

**Comment by cerealisgoodforyou** [comment]
Discord media links are sometimes longer than 200 characters depending on the filename length.

**Comment by Plompi** [comment]
I doubled the maxLength to 400 chars
