### ISSUE TITLE
SoundCloud downloads are entirely broken

### ISSUE THREAD

**Issue by cerealisgoodforyou** [Plompi/VinURL#12]
Attempting to enter a SoundCloud link results in the mod failing to download the song.

As someone else said, maybe switch to cobalt's API?

**Comment by Plompi** [comment]
thanks for pointing out the issue. i set a filter for downloading files via yt-dlp, but that filter didnt contain .opus files, which are used by soundcloud. I will release a new version with the fix the next days.
