### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by Yo-Snowpro** [Plompi/VinURL#15]
I have a modded world and I would love to be able to play custom discs on there

**Comment by Plompi** [comment]
Should be easy to port the mod to 1.21. i will try my best to finish. I will do my best to publish it before next week

**Comment by Yo-Snowpro** [comment]
thanks :D

**Comment by Plompi** [comment]
i published a 1.21 version of the mod. It needed more changed than expected because of the switch to data driven music discs. I tested the mod briefly and it worked for me. If you encounter any problems, dont hesitate to open another issue
