### ISSUE TITLE
is there a mod exacctly like this but client side so i can use it on any server?

### ISSUE THREAD

**Issue by leevee123** [Plompi/VinURL#19]

**Comment by Plompi** [comment]
This mod is designed to be a server/client mod to provide a more natural experience with your friends by sharing the music. There might be other mods that are only client side, but this is the wrong place for such a discussion

**Comment by TheoCGaming** [comment]
if you're still looking for an answer i'd recommend craftify

**Comment by leevee123** [comment]
there was music disk dj but i could never get that mod to work, and its only on older versions
