### ISSUE TITLE
Use cobalt.tools API instead of current YT-Downloader

### ISSUE THREAD

**Issue by Zander-GitHub** [Plompi/VinURL#2]
Usage of cobalt.tools API will allow you to download music from almost any video source, such as Twitter, TikTok, and Instagram.

**Comment by Plompi** [comment]
thanks for the suggestion. YT-DLP can also download from all these sources, here is a [list](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) of all available sites that YT-DLP can download from. Maybe i should change the description of the mod to not only mention Youtube and File-Hosting Sites as a Source for downloading
