### ISSUE TITLE
[Suggestion] Add support for More Jukebox/Noteblock Variants

### ISSUE THREAD

**Issue by TheMasterBlaster** [Plompi/VinURL#20]
Not sure if it would be easy to add, but I would love to see support for the [More Jukebox/Noteblock Variants](https://modrinth.com/mod/more-jukebox-noteblock-variants) mod.

**Comment by Plompi** [comment]
Thanks for the Suggestion. I have already been able to implement the whole thing and requested it as a pull request (`pnk2u/More-Jukebox-Noteblock-Variants#1`) from the mod developer of More Jukebox/Noteblock Variants

**Comment by pnk2u** [comment]
Yup and the version with that compatibility added is now live as 1.0.1. Hope everything works and thanks again for making it work, Plompii! (:

**Comment by pnk2u** [comment]
@TheMasterBlaster Small update: If you had seen my previous comment before, version 1.0.1 included a game-breaking bug, so I removed it but 1.0.2 includes the same compatibility without that bug.

**Comment by TheMasterBlaster** [comment]
Works great! I appreciate the work both of you do! :D
