### ISSUE TITLE
Music download fails in Linux with NoMachine installed

### ISSUE THREAD

**Issue by arp365** [Plompi/VinURL#21]
**Versions:**
- Minecraft: 1.20.1
- Fabric: 0.16.4
- oωo: 0.11.2
- VinURL: 1.1.2

**Steps to reproduce:**
1. Write an URL onto a custom disc
2. Place the disc into a jukebox

**Log:**

```
[Render thread/INFO]: [System] [CHAT] Downloading music, please wait a moment...
[ForkJoinPool.commonPool-worker-1/INFO]: Error relocating /usr/NX/lib/libnxegl.so: __strdup: symbol not found
[ForkJoinPool.commonPool-worker-1/INFO]: [System] [CHAT] Failed to download music!
```

**Posible cause and workaround:**
The problems seems to be related to environment variable LD_PRELOAD since overwriting it to be empty fixes the problem.

**Comment by Plompi** [comment]
Your described issue seems to be caused by noMachine as other users experience the same thing like stated [here](https://forum.nomachine.com/topic/after-uninstall-all-programs-look-for-usr-nx-lib-libnxegl-so). Therefore it has nothing to do with the mod itself.
