### ISSUE TITLE
[BUG] failed to download

### ISSUE THREAD

**Issue by Floppa-is-cool** [Plompi/VinURL#23]
Mc version 1.21.1
Windows 11
Fabric on feather launcher
r cant download music but shows files on folder

**Comment by Plompi** [comment]
Did you try to use the mod on a multiplayer server that doesnt have this mod installed? This mod is a client and serverside mod, so you cant use it everywhere instantly like only client side mods

**Comment by Floppa-is-cool** [comment]
Ser

**Comment by Floppa-is-cool** [comment]
No the server had that my friend was able to playmusic i didnt hear that

**Comment by Floppa-is-cool** [comment]
> Did you try to use the mod on a multiplayer server that doesnt have this mod installed? This mod is a client and serverside mod, so you cant use it everywhere instantly like only client side mods

No the server had that my friend was able to playmusic i didnt hear that
