### ISSUE TITLE
[BUG] Music fails to download

### ISSUE THREAD

**Issue by theUltimateSandMan** [Plompi/VinURL#24]
Anytime I put a music disc with a Youtube Music URL or a normal Youtube URL into a jukebox it always fails to download.

OS: Windows 11
1.20.4

**Comment by Plompi** [comment]
Youtube Music links are not supported, but YouTube links are.

**Comment by theUltimateSandMan** [comment]
Nevermind, I fixed it. If anyone is having the same issue, check in the VinURL folder in your instance folder. If you're using Modrinth, you can access it by clicking "folder" on your instance. In the VinURL folder, open the ffmpeg folder, and make sure both ffmpeg are installed and ffmprobe. You can just search ffmpeg up, download it, extract it, then find ffmpeg.exe and ffmprobe.exe and drag n' drop them into the ffmpeg folder.

**Comment by Plompi** [comment]
I'm glad to hear that you found a fix for the problem. However, ffmpeg should be downloaded automatically by the mod. Have you tried what happens if you delete the vinurl folder and then start Minecraft? FFmpeg and yt-dlp should automatically be reinstalled into the vinurl folder
