### ISSUE TITLE
Kicked from server when using/playing custom record

### ISSUE THREAD

**Issue by TheMasterBlaster** [Plompi/VinURL#3]
Player loses connection from server/client when trying to open GUI or play custom record.

Minecraft version: 1.20.6
Fabric version: 0.15.11

VinURL version: 1.1.1
oωo (owo-lib) versions: 0.12.7 & 0.12.8
Fabric-api version: 0.97.8

[console-log.txt](https://github.com/Plompi/VinURL/files/15205351/console-log.txt)

**Comment by Plompi** [comment]
thanks for the issue, i tested the mod in singleplayer and there it worked perfectly fine but in multiplayer your described issue occurs. i will try to fix it.

**Comment by TheMasterBlaster** [comment]
Just double checked and I'm not getting the crash on single player using Fabric 0.15.11 now, not sure why it was doing it before but sorry about that.

**Comment by Plompi** [comment]
dont be sorry about that, it was an issue with the mod when installed on a server. It should now work with the newest release (1.1.2) of the Mod
